"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from datetime import timedelta
import redis

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

try:
    from dotenv import load_dotenv

    load_dotenv(BASE_DIR / '.env')
except ImportError:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
from django.core.exceptions import ImproperlyConfigured

DEBUG = os.environ.get('DEBUG', 'True').lower() == 'true'
SECRET_KEY = os.environ.get('SECRET_KEY', '').strip()

if not SECRET_KEY:
    raise ImproperlyConfigured("SECRET_KEY environment variable is required.")

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,testserver').split(',')
    if host.strip()
]
if not DEBUG and any('*' in host or host.startswith('.') for host in ALLOWED_HOSTS):
    raise ImproperlyConfigured("ALLOWED_HOSTS must not contain wildcards when DEBUG=False.")


# CORS Configuration: Allow frontend origins
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True' if DEBUG else 'False').lower() == 'true'

# Fallback to explicit origins if CORS_ALLOW_ALL_ORIGINS is False
cors_origins_env = os.environ.get('CORS_ALLOWED_ORIGINS')
if cors_origins_env:
    CORS_ALLOWED_ORIGINS = cors_origins_env.split(',')
else:
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:3001',
        'http://127.0.0.1:3001',
    ]

# CSRF configuration: Trusted origins for state-changing requests
csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS')
if csrf_origins_env:
    CSRF_TRUSTED_ORIGINS = csrf_origins_env.split(',')
else:
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:3000',
        'http://127.0.0.1:3000',
        'http://localhost:3001',
        'http://127.0.0.1:3001',
    ]

# CORS additional headers: allow credentials with credentials=true requests
CORS_ALLOW_CREDENTIALS = True

# CORS allow all methods for preflight
CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
    'HEAD',
]

# Allow common headers in preflight requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-request-id',
    'x-organization-id',
]

# Expose response headers to the frontend
CORS_EXPOSE_HEADERS = [
    'x-request-id',
    'x-organization-id',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'apps.core',
    'apps.organizations',
    'apps.workspaces',
    'apps.projects',
    'apps.tasks',
    'apps.comments',
    'apps.notifications',
    'apps.ai_assistant.apps.AiAssistantConfig',
    'apps.audit_logs',
    'apps.user_profiles',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'config.middleware.RequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'config.middleware.JWTAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'apps.core.middleware.TenantMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if "test" in sys.argv:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
else:
    db_password = os.environ.get("DB_PASSWORD")
    if not db_password:
        if not DEBUG:
            raise ImproperlyConfigured("DB_PASSWORD environment variable is required in production (DEBUG=False).")
        db_password = "12345678"

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("DB_NAME", "collabai_db"),
            "USER": os.environ.get("DB_USER", "postgres"),
            "PASSWORD": db_password,
            "HOST": os.environ.get("DB_HOST", "localhost"),
            "PORT": os.environ.get("DB_PORT", "5432"),
        }
    }


# Cache: Redis when REDIS_URL is set, in-process LocMem otherwise so dev/tests
# work without a running Redis. Default cache TTL is 5 min for list endpoints.
REDIS_URL = os.environ.get('REDIS_URL')
REDIS_AVAILABLE = False

if REDIS_URL:
    try:
        redis_client = redis.from_url(REDIS_URL)
        redis_client.ping()
        REDIS_AVAILABLE = True
    except Exception:
        REDIS_AVAILABLE = False
if "test" in sys.argv:
    # Disable external Redis dependencies during unit testing
    REDIS_URL = None
    REDIS_AVAILABLE = False
CACHE_DEFAULT_TIMEOUT = int(os.environ.get('CACHE_DEFAULT_TIMEOUT', 300))
METRICS_CACHE_TIMEOUT = int(os.environ.get('METRICS_CACHE_TIMEOUT', 60))

if REDIS_AVAILABLE:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'IGNORE_EXCEPTIONS': True,
            },
            'KEY_PREFIX': 'collabai',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
        }
    }
    DJANGO_REDIS_IGNORE_EXCEPTIONS = True
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'collabai-default',
            'TIMEOUT': CACHE_DEFAULT_TIMEOUT,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_PAGINATION_CLASS': 'common.pagination.StandardPagination',
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'common.exceptions.custom_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    # During ``manage.py test`` runs, lift all throttle ceilings to effectively
    # disable rate limiting so tests that hit ``/auth/*`` repeatedly aren't
    # blocked by shared LocMem cache state. Production rates apply otherwise.
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10000/minute' if "test" in sys.argv else os.environ.get('THROTTLE_ANON_RATE', '60/minute'),
        'user': '10000/minute' if "test" in sys.argv else os.environ.get('THROTTLE_USER_RATE', '1000/hour'),
        # Per-endpoint brute-force protection (ScopedRateThrottle)
        'auth_login': '10000/minute' if "test" in sys.argv else os.environ.get('THROTTLE_AUTH_LOGIN_RATE', '5/minute'),
        'auth_register': '10000/minute' if "test" in sys.argv else os.environ.get('THROTTLE_AUTH_REGISTER_RATE', '3/minute'),
        'auth_refresh': '10000/minute' if "test" in sys.argv else os.environ.get('THROTTLE_AUTH_REFRESH_RATE', '10/minute'),
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'CollabAI API',
    'DESCRIPTION': 'API documentation for CollabAI.',
    'VERSION': '1.0.0',
    'SECURITY': [{'bearerAuth': []}],
    'ENUM_NAME_OVERRIDES': {
        'MemberRoleEnum': [
            ('admin', 'Admin'),
            ('manager', 'Manager'),
            ('member', 'Member'),
        ],
    },
    'COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME_MINUTES', 60))),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME_DAYS', 7))),
    'ROTATE_REFRESH_TOKENS': os.environ.get('JWT_ROTATE_REFRESH_TOKENS', 'True').lower() == 'true',
    'BLACKLIST_AFTER_ROTATION': os.environ.get('JWT_BLACKLIST_AFTER_ROTATION', 'True').lower() == 'true',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

API_JWT_ENFORCE_PREFIX = '/api/v1/'
API_JWT_PUBLIC_PATHS = (
    '/api/v1/auth/register',
    '/api/v1/auth/login',
    '/api/v1/auth/refresh',
    '/api/v1/auth/forgot-password',
    '/api/v1/auth/reset-password',
    '/api/v1/health',
)
API_JWT_ROLE_REQUIREMENTS = ()
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'config.middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'apps.ai_assistant': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# --- RAG / AI (local dev) ---
GROQ_API_KEY = (os.environ.get('GROQ_API_KEY') or '').strip().strip('"').strip("'")
GROQ_MODEL = os.environ.get('GROQ_MODEL', 'llama-3.1-8b-instant')
RAG_EMBEDDING_MODEL = os.environ.get(
    'RAG_EMBEDDING_MODEL',
    'sentence-transformers/all-MiniLM-L6-v2',
)
RAG_EMBEDDING_DIMS = int(os.environ.get('RAG_EMBEDDING_DIMS', '384'))
RAG_VECTOR_INDEX_NAME = os.environ.get('RAG_VECTOR_INDEX_NAME', 'collabai_rag')
RAG_TOP_K_DEFAULT = int(os.environ.get('RAG_TOP_K_DEFAULT', '5'))
RAG_AUTO_INDEX = False if "test" in sys.argv else os.environ.get('RAG_AUTO_INDEX', 'true').lower() == 'true'
# Use in-memory vector search when Redis Stack / RediSearch is unavailable.
RAG_FORCE_MEMORY_STORE = (
    "test" in sys.argv
    or not REDIS_AVAILABLE
)
# --- Celery (optional; eager mode works without a worker) ---
if "test" in sys.argv:
    CELERY_BROKER_URL = 'memory://'
    CELERY_RESULT_BACKEND = 'cache+memory://'
    CELERY_TASK_ALWAYS_EAGER = True
else:
    CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', REDIS_URL or 'redis://127.0.0.1:6379/1')
    CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
    CELERY_TASK_ALWAYS_EAGER = os.environ.get(
        'CELERY_TASK_ALWAYS_EAGER',
        'true' if DEBUG else 'false',
    ).lower() == 'true'
CELERY_TASK_EAGER_PROPAGATES = True

# --- Production Security Hardening Headers ---
SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.environ.get('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() == 'true'
SECURE_HSTS_PRELOAD = os.environ.get('SECURE_HSTS_PRELOAD', 'False').lower() == 'true'

SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', 'True' if not DEBUG else 'False').lower() == 'true'

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True

if os.environ.get('SECURE_PROXY_SSL_HEADER_ENABLED', 'False').lower() == 'true':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend' if DEBUG else 'django.core.mail.backends.smtp.EmailBackend',
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "CollabAI <noreply@collabai.local>")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")
