# Generated by Django 6.0.4 on 2026-05-23 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
        ('organizations', '0005_update_org_member_roles_to_4role_rbac'),
        ('tasks', '0002_seed_default_task_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='airequest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['organization', 'user', 'created_at'], name='ai_assistan_organiz_3f73ad_idx'),
        ),
        migrations.AddIndex(
            model_name='airequest',
            index=models.Index(fields=['user', 'created_at'], name='ai_assistan_user_id_3c2ece_idx'),
        ),
    ]
